import Search from "@/components/search";
import "./globals.css";
import CartIcon from "@/components/cartIcon";
import Image from "next/image";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

      >
        <main className="bg-[#ede7bf]">
          <nav className="w-full h-[50px]  flex justify-center capitalize items-center text-white fixed bg-[#3b82f6] z-20">
            <figure className="w-[200px] flex justify-center items-center">
              <Image className="object-cover" src='/iphonelogo.png' width={40} height={40} alt='logo' />
            </figure>
            <ul className=" *:m-5 flex justify-end items-center">
              <div className="*:px-5 hidden lg:flex">
              <li><Link href='./'>Products</Link></li>
              <li>mac</li>
              <li>ipad</li>
              <li>iphone</li>
              <li>watch</li>
              </div>
              <li className="w-[200px] md:w-[500px]">
                <Search />
              </li>
              <li><CartIcon /></li>

            </ul>
          </nav>

          {children}
        </main>

      </body>
    </html>
  );
}
